apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisordvan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervisordvan
  template:
    metadata:
      labels:
        app: supervisordvan
    spec:
      containers:
      - image: budtmo/docker-android:emulator_11.0
        name: supervisordvan

---

apiVersion: v1
kind: Service
metadata:
  name: supervisordvan
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "supervisordvan"
    port: 6080
  selector:
    app: supervisordvan
